services:
  db:
    image: postgres:latest
    container_name: catsgram_db
    environment:
      POSTGRES_DB: catsgram
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: